name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
          
          - name: List and Read files
            run: |
                echo "First Action"
                ls -ltra
                cat README.md

          # - name: Generate ASCII Artwork
          #   run: cowsay -f dargon "RUN for COVER, I am a DRAGON....RAWR" >> dargon.txt
          
