name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
          
          - name: Welcome Message
            run: echo "First action"
          
          - name: List files
            run: ls -al

          - name: Read files
            run: cat README.md