name: Matrix Config

on:
    workflow_dispatch: 
    push:


jobs:
    deploy-on-ubuntu:
        strategy:
          matrix:
            os: [ubuntu-latest,windows-latest]
            images: [hello-world,alpine]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Echo Docker Details
              run: docker info
            
            - name: Run Image on ${{ matrix.os }}
              run: docker run ${{ matrix.images }}
            
    # deploy-on-windows:
    #     runs-on: windows-latest
    #     steps:
    #         - name: Echo Docker Details
    #           run: docker info
          
    #         - name: Run Image
    #           run: docker run hello-world